version: '3'

vars:

dotenv: ['.env']

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Build tasks
  build-recursive:
    desc: Build the binary using dev script
    cmds:
      - mkdir -p ./bin
      - ./dev/ci/presubmits/go-build.sh

  build:
    desc: Build single binary for current platform
    cmds:
      - mkdir -p ./bin
      - go build -o ./bin/kubectl-ai ./cmd

  # Run tasks
  run:
    desc: Run the application
    cmds:
      - go run ./cmd

  run-html:
    desc: Run with HTML UI
    cmds:
      - go run ./cmd --user-interface html

  # Code quality tasks using existing dev scripts
  fmt:
    desc: Format code using dev script
    cmds:
      - ./dev/tasks/format.sh

  vet:
    desc: Run go vet using dev script
    cmds:
      - ./dev/ci/presubmits/go-vet.sh

  tidy:
    desc: Tidy go modules using dev script
    cmds:
      - ./dev/tasks/gomod.sh

  # Verification tasks (CI-style checks)
  verify-format:
    desc: Verify code formatting
    cmds:
      - ./dev/ci/presubmits/verify-format.sh

  verify-gomod:
    desc: Verify go.mod files are tidy
    cmds:
      - ./dev/ci/presubmits/verify-gomod.sh

  verify-autogen:
    desc: Verify auto-generated files are up to date
    cmds:
      - ./dev/ci/presubmits/verify-autogen.sh

  # Generation tasks
  generate-actions:
    desc: Generate GitHub Actions workflows
    cmds:
      - ./dev/tasks/generate-github-actions.sh

  # Evaluation tasks
  run-evals:
    desc: Run evaluations (periodic task)
    cmds:
      - ./dev/ci/periodics/run-evals.sh

  analyze-evals:
    desc: Analyze evaluations (periodic task)
    cmds:
      - ./dev/ci/periodics/analyze-evals.sh

  # Combined tasks
  check:
    desc: Run all verification checks (presubmit-style)
    cmds:
      - task: verify-format
      - task: verify-gomod
      - task: verify-autogen
      - task: build-recursive
      - task: vet

  # Development workflow
  dev:
    desc: Development mode - build and run
    deps: [build]
    cmds:
      - ./bin/kubectl-ai

  dev-html:
    desc: Development mode - build and run with HTML UI
    deps: [build]
    cmds:
      - ./bin/kubectl-ai --user-interface html

  # Maintenance tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf ./bin
      - rm -f coverage.out coverage.html

  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  update-deps:
    desc: Update dependencies and tidy
    cmds:
      - go get -u ./...
      - task: tidy

  # Installation
  install:
    desc: Install the binary
    deps: [build]
    cmds:
      - cp ./bin/kubectl-ai $(go env GOPATH)/bin/

  # Testing (basic - extend based on your test setup)
  test:
    desc: Run tests
    cmds:
      - go test ./...

  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html