kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubectl-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-ai
  template:
    metadata:
      labels:
        app: kubectl-ai
    spec:
      serviceAccountName: kubectl-ai
      containers:
      - name: kubectl-ai
        image: kubectl-ai:latest
        args:
        - --user-interface=html
        envFrom:
        - secretRef:
            name: kubectl-ai
---

kind: Secret
apiVersion: v1
metadata:
  name: kubectl-ai
  labels:
    app: kubectl-ai
type: Opaque

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubectl-ai

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-ai:view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: kubectl-ai

---

kind: Service
apiVersion: v1
metadata:
  name: kubectl-ai
  labels:
    app: kubectl-ai
spec:
  selector:
    app: kubectl-ai
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
